/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ImportacoesRouteImport } from './routes/importacoes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConfiguracoesAutomacaoRouteImport } from './routes/configuracoes/automacao'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportacoesRoute = ImportacoesRouteImport.update({
  id: '/importacoes',
  path: '/importacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesAutomacaoRoute = ConfiguracoesAutomacaoRouteImport.update({
  id: '/configuracoes/automacao',
  path: '/configuracoes/automacao',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/importacoes': typeof ImportacoesRoute
  '/login': typeof LoginRoute
  '/configuracoes/automacao': typeof ConfiguracoesAutomacaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/importacoes': typeof ImportacoesRoute
  '/login': typeof LoginRoute
  '/configuracoes/automacao': typeof ConfiguracoesAutomacaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/importacoes': typeof ImportacoesRoute
  '/login': typeof LoginRoute
  '/configuracoes/automacao': typeof ConfiguracoesAutomacaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/importacoes' | '/login' | '/configuracoes/automacao'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/importacoes' | '/login' | '/configuracoes/automacao'
  id: '__root__' | '/' | '/importacoes' | '/login' | '/configuracoes/automacao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImportacoesRoute: typeof ImportacoesRoute
  LoginRoute: typeof LoginRoute
  ConfiguracoesAutomacaoRoute: typeof ConfiguracoesAutomacaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importacoes': {
      id: '/importacoes'
      path: '/importacoes'
      fullPath: '/importacoes'
      preLoaderRoute: typeof ImportacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes/automacao': {
      id: '/configuracoes/automacao'
      path: '/configuracoes/automacao'
      fullPath: '/configuracoes/automacao'
      preLoaderRoute: typeof ConfiguracoesAutomacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImportacoesRoute: ImportacoesRoute,
  LoginRoute: LoginRoute,
  ConfiguracoesAutomacaoRoute: ConfiguracoesAutomacaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
